language: cpp
sudo: required
compiler:
  - clang
os: linux
dist: trusty

env:
  global:
    - MAKE_THREADS=2
    - PYTHON_VERSION="2.7"
    - STACK_SRC="${TRAVIS_BUILD_DIR}/tmp"
    - PACKAGES_DIR="${TRAVIS_BUILD_DIR}/opt"
    - PETSC_DIR="${PACKAGES_DIR}/petsc-3.7.4"

addons:
  apt:
    packages:
    - cmake
    - automake
    - gfortran
    - curl
    - valgrind

# Limit number of commits in cloning
git:
  depth: 200

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - chmod a+x scripts/travis-install-deps.sh
  - if [ ! -d ${PACKAGES_DIR}/libmesh ]; then scripts/travis-install-deps.sh; else echo "Using cached dependencies."; fi
  - ls -R ${PACKAGES_DIR}

script:
  - chmod a+x scripts/set-env-mpich.sh; scripts/set-env-mpich.sh
  - mkdir build
  - pushd build
  - CC=${PACKAGES_DIR}/mpich-3.2/bin/mpicc CXX=${PACKAGES_DIR}/mpich-3.2/bin/mpicxx cmake -DLIBMESH_DIR:PATH=${PACKAGES_DIR}/libmesh -DBUILD_SHARED_LIBS:BOOL=ON -DENABLE_TESTING:BOOL=ON ../
  - make -j $MAKE_THREADS
  - ./test_main

cache:
  timeout: 300
  directories:
    - ${PACKAGES_DIR}

notifications:
  email: false